# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_auto_20180201_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created',)},
        ),
    ]
