# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_auto_20180205_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptiontag',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
