# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link_github',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
