# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_link_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='--------', max_length=200),
        ),
    ]
